-- Fase 4 — faturamento separado por canal.
-- Ele vende nos dois: catálogo (atacado) e balcão/feira (varejo). Somados num
-- número só, não dá para saber qual das duas pernas sustenta a loja.
--
-- Retorna canal, vendas, peças, bruto, desconto, frete, total e participação.
-- Corpo em `12_funcoes_canonicas.sql`, junto das demais funções.
